### ISSUE TITLE
rpm-ndb and rpm conflict during kiwi build

### ISSUE THREAD

**Issue by mfriesenegger** [SUSE-Enceladus/keg-recipes#178]
I am using the develop branch for testing.  cross-cloud/sles/byos/15-sp4 defines rpm-ndb in data/base/common/sle15/sp2/packages.yaml and rpm in data/base/common/sle15/packages.yaml.  Attempting to build the definition with kiwi produces the following error

DEBUG: 07:17:20 | system: Problem: the to be installed rpm-ndb-4.14.3-150300.49.1.x86_64 conflicts with 'rpm' provided by the installed rpm-4.14.3-150300.49.1.x86_64
DEBUG: 07:17:20 | system:  Solution 1: deinstallation of rpm-4.14.3-150300.49.1.x86_64
DEBUG: 07:17:20 | system:  Solution 2: do not install rpm-ndb-4.14.3-150300.49.1.x86_64
DEBUG: 07:17:20 | system: Choose from above solutions by number or cancel [1/2/c/d/?] (c): c
ERROR: 07:17:20 | KiwiInstallPhaseFailed: System package installation failed:

**Comment by rjschwei** [comment]
Please provide the keg command. No description should be generated that has this conflict as the namespace that contains rpm should be over written.

**Comment by mfriesenegger** [comment]
keg --recipes-root=/root/keg-recipes --dest-dir=/root/cross-cloud_sles_byos_15-sp4 cross-cloud/sles/byos/15-sp4

**Comment by jgleissner** [comment]
I'm guessing this is a manual kiwi run, correct? The generated config.kiwi contains a comment with `OBS-IgnorePackage: rpm` which tells OBS to ignore `rpm` but that has no effect outside OBS and kiwi installs `rpm` instead of `rpm-ndb` when bootstrapping the build system. As a work-around, adding ` --add-bootstrap-package=rpm-ndb` might help.

**Comment by jgleissner** [comment]
I think we could fix that in keg-recipes by moving `rpm-ndb` into the bootstrap section. This would probably make `OBS-IgnorePackage: rpm` obsolete too.

**Comment by rjschwei** [comment]
No, the directive would not be obsolete because of other rpm entanglements. Yes, putting `rpm-ndb` into the bootstrap section should resolve the issue for building images outside of the build service.

**Comment by jgleissner** [comment]
Fix merged.

**Comment by jgleissner** [comment]
For the record, moving `rpm-ndb` to the bootstrap section fixes the conflict, but unless you have `rpm-ndb` installed on your build host, you still can't build the image directly with kiwi. Kiwi uses the build host's rpm to install the bootstrap packages, and if that rpm uses the Berkeley db backend, the rpm db of the target system will be created in Berkeley db format and installation of `rpm-ndb` will fail.

The build system when bootstrapping the build environment seems to prevent that (and perhaps other issues) by pre-installing a bunch of core packages including the package manager into the build system. Pre-installing means it just copies the rpm contents, not an rpm install. Perhaps something like that could be implemented in kiwi as well.
